### PR TITLE
Adding a write-up of RPG from 2019-10-23 session

### PR DESCRIPTION
**Pull request by simon-r-white**
Right, attempt two, making the pull request against the right repo.

Again, this is a more complete write-up of the RPG - it will need to be cut down for the blog post, but I thought I'd write something now while I remembered.

### CODE REVIEW

**Comment by flodskum** [comment]
Cool!  Maybe we should have a section/posts for RPG story write ups?

**Comment by simon-r-white** [comment]
Possibly, though I don't think we should force anyone to do a write up.

A proper session report, noting mechanical bits of the system and greater detail can be a lot of work.

Since I used my new toy (whiteboards/placemats) I don't have any character sheets or other details to write a better summary (didn't even snap a photo of our 'map'). This was all from memory yesterday lunch.

Saying all that, I'm happy to have the write up posted in full to a new section. Might need to copy+paste previous session summaries to populate it a bit.

I wouldn't drop the one paragraph summary from the blog post though. I think that gives a good overview of what happens at each session.

**Comment by NightB1ade** [comment]
Sounds definitely interesting for a section as we get more ongoing games too.

I'll warn now that I am rubbish writing stuff up for reading.  So if I'm running games, I probably won't get enough time to do it between sessions.....

Agreed on what we would populate the section with at this moment would be the question

**Comment by flodskum** [comment]
Suggested way of having the session in the site - see #38 
Currently just links from the blog article, but we could add a different section.

**Comment by NightB1ade** [comment]
Closing this as #38 covers this now

**Pull request closed without merging**
