### PR TITLE
Initial games

### PR DESCRIPTION
**Pull request by flodskum**
Note: Work in progress but could go in if you are happy.

### CODE REVIEW

**Comment by flodskum** [comment]
Feedback

> Long-ish pages, makes me think that we need some contents to it
> Hanabi BGG link is not capitalised
> "Co op" looks kinda weird to me, would "Co-op" be better?
> Catherine says, we should make it clear that these games are example/subset of our games, Not all of them
> Also, since StIvesTabletop has its own BGG account - when we can populate it with "played games" and that can be linked to (possibly after a few sessions)

**Comment by NightB1ade** [comment]
Kingdomino:
The picture shows only two kings on the line, but in 2-player, you have both kings out at a time
The scoring doesn't need to have the castle in the centre, but you get 10 bonus points for doing so

**Comment by flodskum** [comment]
FYI - addressed feedback apart from TOC - also added DnD section

**Comment by flodskum** [comment]
Now with TOC!

**Comment by flodskum** [comment]
> Kingdomino:
> The picture shows only two kings on the line, but in 2-player, you have both kings out at a time
> The scoring doesn't need to have the castle in the centre, but you get 10 bonus points for doing so

K knows the picture is a bit wrong but the caption is just contents and its mostly right... :)

**Comment by flodskum** [comment]
LGTM - your clean ups. I resolved the conflict with master.
Happy to merge?

**Comment by NightB1ade** [comment]
I think the pages eventually need a "Back to top" link, but that can come later.

**Review by NightB1ade — APPROVED** [review]

**Pull request merged**
